version: "3.7"
services:
  read-logs-server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: "read-logs-server"
    command: python -u app.py
    volumes: 
      - /tmp/project_logs:/code/logs
      - ./:/code
    ports: 
      - "9700:5000"
    logging:
      options:
        max-file: "3"
        max-size: "50m"
